### ISSUE TITLE
gad gateway 502 when replying to quiz question

### ISSUE THREAD

**Issue by lindaudby** [McStasMcXtrace/McWeb#104]
In Ku2017 course in quiz "reciprocal lattice of Ni", question 2. When replying correctly
![screenshot from 2017-05-11 12-30-18](https://cloud.githubusercontent.com/assets/15801156/25945070/e76ff90e-3645-11e7-92e2-f1b8fef9a01b.png)
I get Bad getway error
![screenshot from 2017-05-11 12-30-34](https://cloud.githubusercontent.com/assets/15801156/25945085/f53b3ddc-3645-11e7-9312-9452d88b8857.png)

The students will work with teh quiz on Monday so will appreciate quick resolve :)

**Comment by willend** [comment]
@lindaudby it will likely not be fixed during this long bank-holiday + weekend, but if you pasted the relevant URL and math formula here it would make it easier to reproduce quickly...

**Comment by lindaudby** [comment]
The quiz url is this  https://www.e-neutrons.org/moodle/mod/quiz/view.php?id=2077
The problem I think is not the math formula but simply that replying to the quiz question 2 somehow gives the bad gateway error ...? And now whenever I try to continue the quiz I get the bad gateway error too so can't even copy paste the formula:/

**Comment by willend** [comment]
The issue comes from one of the "extra" moodle packages installed - i.e. not from the main moodle software:

<pre>
PHP message: PHP Notice:  Undefined property: qtype_algebra_parser_bracket::$_sign in /home/srv/mcweb/moodle/question/type/algebra/parser.php on line 1339
PHP message: PHP Notice:  Undefined property: qtype_algebra_parser_bracket::$_sign in /home/srv/mcweb/moodle/question/type/algebra/parser.php on line 1339
PHP message: PHP Notice:  Undefined property: qtype_algebra_parser_bracket::$_sign in /home/srv/mcweb/moodle/question/type/algebra/parser.php on line 1339
PHP message: PHP Notice:  Undefined property: qtype_algebra_parser_bracket::$_sign in /home/srv/mcweb/moodle/question/type/algebra/parser.php on line 1339
PHP message: PHP Notice:  Undefined property: qtype_algebra_parser_bracket::$_sign in /home/srv/mcweb/moodle/question/type/algebra/parser.php on line 1339
PHP message: PHP Notice:  Undefined property: qtype_algebra_parser_bracket::$_sign in /home/srv/mcweb/moodle/question/type/algebra/parser.php on line 1339
PHP message: PHP Notice:  Undefined property: qtype_algebra_parser_bracket::$_sign in /home/srv/mcweb/moodle/question/type/algebra/parser.php on line 1339
PHP message: PHP Notice:  Undefined property: qtype_algebra_parser_bracket::$_sign in /home/srv/mcweb/moodle/question/type/algebra/parser.php on line 1339
</pre>
- which is exactly why I want to get rid of as many of these non-standard "bells and whistles" pieces of software as possible...

**Comment by willend** [comment]
I think I may have been able to monkey-patch the software now, and you are probably able to continue the questions...

It does however not solve the underlying problem of having to apply local patches everywhere that may get overwritten on updating software from the repository of updated moodle modules...

**Comment by lindaudby** [comment]
It works now! Thanks for solving/patching nevertheless:)
