### ISSUE TITLE
Description for nogle parametre vises ikke, hvis der er mange parametre i et instrument

### ISSUE THREAD

**Issue by PJRay** [McStasMcXtrace/McWeb#113]
F.eks. https://sim.e-neutrons.org/instrument-menu/facilities_ILL/ILL_H10_IN8

Parameteren EI har en description under %Parameters kommentaren i selve instrument-filen, men på siden for instrumentet, og på documentation siden (https://sim.e-neutrons.org/static/doc/facilities_ILL/ILL_H10_IN8.html) vises denne ikke.

Er der noget overflow for antal parameter-beskrivelser, eller er det noget med at dette (lettere avancerede) instrument includerer en template?

**Comment by willend** [comment]
The instr in question is assembled using the %include keyword. I believe this explains the missing parameter info, since these strings are taken directly from the instr file, not generated via the instrument binary.

A workaround is to simply concatenate the instrument files, i.e. not use %include...

**Comment by willend** [comment]
For now we "wontfix" this one, since solving this would be more of a McStas issue. Workaround is to avoid %included instrument  files
