### ISSUE TITLE
elearn1 cannot edit wiki links

### ISSUE THREAD

**Issue by lindaudby** [McStasMcXtrace/McWeb#121]
![screenshot from 2017-08-22 10-35-51](https://user-images.githubusercontent.com/15801156/29556417-161c8e30-8726-11e7-9169-b4e513759474.png)
The wiki links which were copied with the course modules work fine. But when I try to edit existing or make new ones I cannot get the link creator to even accept the input without https://elearn1.dtu.dk- See attachment.

**Comment by lindaudby** [comment]
and If I then input the full URL https://elearn1.dtu.dk[restofpath] I get an extra page when clicking the link which I don't get in the wikilinks without the full paths.
![screenshot from 2017-08-22 10-40-26](https://user-images.githubusercontent.com/15801156/29556588-8c48693a-8726-11e7-95f4-2744735fd212.png)

**Comment by willend** [comment]
What is not clear in the above is that this only happens when adding an "external URL" via the "Add activity or ressource" dialogue.

Various workarounds/solutions possible:
 * Use “assignment” instead and make a link in “description”, to be “included on course page”.
 * Use the full URL including http(s)://example.org/localurl/pointing/somewhere and use strip the URL's if moving data to another installation (manually or using https://github.com/McStasMcXtrace/McWeb/blob/master/scripts/moodle_strip_mbz_URLS)
 
Also awaiting input from https://moodle.org/mod/forum/discuss.php?d=357241
