### ISSUE TITLE
McWeb dynamic list of instrument files

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#13]
- All users have access to all instrs (remove group membership requirement)
- Shown "instrument group" should be extracted from URL e.g. 
https://mcwww.mccode.org/SomeGroup/job/y8jkwrHwWpKd/#
- If "unset" use instrument group "default" corresponding to a link in the filesystem

**Comment by jaga-mcstas** [comment]
This task has been completed. 

Various notes: The html/js implementation has two peculiar needs in order to switch between instrument groups: 1) A page refresh in order to update the instrument list 2) a new job database instance. If this is not satisfied, the form assumes that it is dealing with the "original" instrument group, because the instrument is pulled from the list by index number, not string identifier. This is only updated if the job instance is updated.

Furthermore, an automatic page refresh has been introduced when clicking "Run" and getting a success result. This refreshes the job instance. If you click another instrument or group, it would be refreshed automatically, but, if the user does not, and instead changes some params values, the simrun would contain the OLD params values anyway.

**Comment by willend** [comment]
Solved in not-yet-uploaded rework of mcweb

**Comment by willend** [comment]
Closing this one as we have a solution in the pipe
