### ISSUE TITLE
site name e-neutrons/sim possible?

### ISSUE THREAD

**Issue by lindaudby** [McStasMcXtrace/McWeb#138]
Not sure where or how to post this, but would it be possible to have the same names for the various parts of e-neutrons as in elearn1? (I may have forgotten why in case the answer is no)

If config was a similar setup as e-neutrons/wiki, e-neutrons/sim, e-neutrons/moodle, then we wouldn't have to use absolute URLs to instruments in simulators (now have to correct them for all activities in all courses in each transfer between elearn1 and e-neutrons).

**Comment by willend** [comment]
The issue is that our "McWeb" django application running the simulator etc. wants to "live" at / in a webserver, i.e. sim.e-neutrons.org. - And a e-neutrons.org we also want a nicely looking "starting page" (wordpress).

I tried making this work in the past, but simply couldn't make it work like what you describe. 

One way to make it work would be that the wordpress site only lives at www.e-neutrons.org - and the rest of the sites at e-neutrons.org... There are pros and cons...

Let's discuss face to face at next e-neutrons day.

**Comment by willend** [comment]
- But actually, it sort of does work, because of a redirect:

https://www.e-neutrons.org/sim/instrument/intro-ns/reflectometer points to https://sim.e-neutrons.org/instrument/intro-ns/reflectometer

**Comment by lindaudby** [comment]
Ah, my bad, sorry.
I tried with a relative /sim/instrument adress which didn't seem to work, but now it does. Maybe just typo.
