### ISSUE TITLE
Different bahaviour of PSDlin_diff_monitor.comp in mcweb

### ISSUE THREAD

**Issue by lindaudby** [McStasMcXtrace/McWeb#166]
The component is used in Radiography_absorbing_edge.instr and running with standard parameters on my McStas 2.3
![edge_monitor_50mum dat](https://user-images.githubusercontent.com/15801156/30665670-0af155fc-9e52-11e7-959f-179e8a20aac6.png)

But running the same instrument with the same component on McWeb
https://sim.e-neutrons.org/instrument-menu/swedness/Radiography_absorbing_edge gives
 http://sim.e-neutrons.org/static/data/udby_Radiography_absorbing_edge_20170920_192948/browse.html 
![screenshot from 2017-09-20 22-19-25](https://user-images.githubusercontent.com/15801156/30665707-36769264-9e52-11e7-9dd1-4173929ecbab.png)

I can't figure out why the x-range on the linear monitor in McWeb is different than the one in my McStas?

**Comment by willend** [comment]
I believe I upgraded to mcstas 2.4.1 on e-neutrons, so it may be due to a minor difference between the versions. Will check later today.

**Comment by lindaudby** [comment]
Thanks :)

**Comment by willend** [comment]
Found the issue, nothing to do with McStas versions (machine runs 2.3 like yourself), but an overrun array in the non-standard PSDlin_diff_monitor.comp.

You have shortened not only the PSDdiff_ oriented arrays, but also PSDlin_p2 - meaning that lots of memory is shifted around by 1 double...! - have a look here, PSDlin_p2 is of length nx-1 and needs to be of length nx just like the other related arrays.

<pre>
DECLARE
  %{
    double PSDlin_N[nx];
    double PSDlin_p[nx];
    double PSDlin_p2[nx-1];
    double PSDdiff_N[nx-1];
    double PSDdiff_p[nx-1];
    double PSDdiff_p2[nx-1];
    int i;
    char difilename[128];
  %}
</pre>

For some reason, the error did not show as often when not running with MPI - but that is sheer luck!

My speculation is further that you have experienced other strangeness from the component - because this code is also non-standard - and would never happen if the other mishap was not around...
<pre>
      if((i >= nx) || (i<0))
      {
        printf("FATAL ERROR: wrong positioning in linear PSD. i= %i \n",i);
        exit(1);
      }
</pre>

Morale is:
Don't use non-standard components. Use existing, more well tested solutions. And if what you need does not exist, better contribute your own developments to McStas via GitHub, which will allow others to look closer / experience / fix bugs...

**Comment by willend** [comment]
Things now work as expected, see http://sim.e-neutrons.org/static/data/mcstas_Radiography_absorbing_edge_20170921_084448/browse.html

I have modfied all local copies of the comp at mcstas-01.risoe.dk and will send you the comp via email for your reference

**Comment by lindaudby** [comment]
Hi Peter,
thanks alot for taking a look and fixing the bug! I think the component was actually developed/prototyped by you as part of the collaboration with Markus on this exercise so I guess it is safe now to upload to mcweb and commit  to github?

**Comment by willend** [comment]
Yes, will make it "official". (And probably I was part of that comp myself...) But it shows exactly what at typical weakness of pushing local comps around can be... ;-)

**Comment by lindaudby** [comment]
I'm sorry it was a bit meesy. But I'm really greatfull for your help in developing the component, otherwise the exercise to measure the blur would not be possible :)
