### ISSUE TITLE
e-neutrons: Finishing the subpage: ABOUT E-NEUTRONS 

### ISSUE THREAD

**Issue by juliehougaard** [McStasMcXtrace/McWeb#52]

**Comment by lindaudby** [comment]
ATM most of the text which needs to be there is present but page format with logoes always it the bottom of page is not optimal. I'm mailing with Troels to get a more flexible solution.
Missing list of contributors.

**Comment by willend** [comment]
Looks to me as if this is now DONE apart from the addition of a DTU logo (which I think is fair since we are developing the platform + running the server... ;-) )

**Comment by lindaudby** [comment]
The logos at the bottom of the page were intented to reflect the funding 
(UCPH actually co-sponsored significantly over the years which is why 
the logo is there).
Of course I have no objections to having a DTU logo on the page, but we 
should probbaly place it together with the team description instead then?

On 01/12/2016 03:11 PM, Peter Willendrup wrote:
>
> Looks to me as if this is now DONE apart from the addition of a DTU 
> logo (which I think is fair since we are developing the platform + 
> running the server... ;-) )
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/McStasMcXtrace/McWeb/issues/52#issuecomment-170922886>.
>


-- 
----------~oOo~----------
Dr. Linda Udby
Associate Professor
X-ray and Neutron Science
Niels Bohr Institute
University of Copenhagen
tel: +45 23 83 98 77
----------~oOo~----------
