### ISSUE TITLE
Uploader: Django upload app

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#7]
Mark has promised to make this available to us - probably as a standalone django app

**Comment by jaga-mcstas** [comment]
We have fixed the uploader to work locally (untested on deployment setup). Group input is a string, no drop down selection as of now. NOTE: The uploader requires a dedicated nginx location and uwsgi process at the moment, since it is separated from the django app at-large. I figure we should probably include it in general django deployment...(?)

Changing the group text input field into a dropdown might require js and a bit of fiddling.

**Comment by willend** [comment]
Hi there, excellent! :-) For the time being, I think a dedicated location and a uwsgi of its own is OK - also for the reason that this is in a way an 'optional' thing - for admin use only. For the same reason, the text input field will also do. Maybe put the list of available (existing) groups on the view? (How does it work btw - if one gives a non-existent group name, will that be created by an mkdir?

**Comment by jaga-mcstas** [comment]
Lovely that the server is up and running again. I guess the upload app works just like you describe, once we have added those two details =) 1) mkdir 2) groups visible in view. 

However, we may need to run a "syncdb" whenever a new group is added - this should be added to the cron job which also compiles the new instrument(s).

**Comment by climbcat** [comment]
an upload app has been (re)written and is located at http://sim.e-neutrons.org/upload/

**Comment by willend** [comment]
Apart from polishing (potential upload to the datafiles folder) this one is now DONE
